### ISSUE TITLE
Calculating product of cardinalities in IDensityMeasure.ifRemoved

### ISSUE THREAD

**Issue by majidalfifi** [kijungs/dcube#1]
Hi @kijungs 

When we calculate the new density after removing tuples, shouldn't we also recalculate cardinalities of all dimensions not just the current dimension we are considering?
I noticed in the code below we are multiplying the new cardinality for the current dimension by the previous cardinalities of other dimensions:

```
public double ifRemoved(int attribute, int numValues, long sumOfMasses) {
    return density(this.mass - sumOfMasses, productOfCardinalities / cardinalities[attribute] * (cardinalities[attribute] - numValues));
}
```

For example, using the `example-data.txt` (geometric, density policy) we get the following densities on for the original three dimensions:

```
mode = 0
tempScore = 728.3424310595163
mode = 1
tempScore = 630.9561104843024
mode = 2
tempScore = 299.7619688308371
```
But if we update all dimensions cardinalities after deleting values from a dimension we get the following:

```
mode = 0
tempScore = 728.40489286
mode = 1
tempScore = 634.337483664
mode = 2
tempScore = 330.170062101
```

Is this a bug or by design?

**Comment by kijungs** [comment]
@majidalfifi 

Hello, thanks for pointing this out. Actually, this is by design for rapid computation.
To recompute the cardinalities of other dimensions, we have to access tuples (i.e., tensor entries), which may be stored in disk.
Repeatedly recomputing the cardinalities should make algorithm much slower.
Thus, in the current implementation, as we delete attribute values in one dimension, we may have attribute values with zero attribute masses in the other dimensions. The attribute values in the other dimensions are not deleted immediately but will be deleted when their corresponding dimensions are updated.

**Comment by majidalfifi** [comment]
@kijungs Aha! Thanks for the quick response and for the clarification.
